# Generated by Django 6.0.1 on 2026-04-27 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0002_alter_expediente_apellido_m'),
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donador',
            fields=[
                ('id_donador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_p', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_m', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('CEI', 'CEI'), ('CANFRO', 'CANFRO'), ('OYE', 'OYE')], default='CEI', max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estatus', models.CharField(default='Activo', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('nota', models.TextField(blank=True, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('localidad', models.CharField(default='Oaxaca', max_length=50)),
                ('pais', models.CharField(default='México', max_length=50)),
                ('beneficiarios_apoyados', models.ManyToManyField(blank=True, db_table='beneficiario_donador', related_name='padrinos', to='beneficiarios.beneficiario')),
            ],
            options={
                'verbose_name_plural': 'Donadores',
                'db_table': 'donador',
            },
        ),
        migrations.CreateModel(
            name='DonativoDonador',
            fields=[
                ('id_donativo', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('id_donador', models.ForeignKey(db_column='id_donador', on_delete=django.db.models.deletion.CASCADE, related_name='donativos', to='donadores.donador')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.PROTECT, related_name='donativos_periodo', to='periodos.periodo')),
            ],
            options={
                'verbose_name_plural': 'Donativos',
                'db_table': 'donativo_donador',
            },
        ),
    ]
