# Generated by Django 6.0.1 on 2026-04-15 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0004_fotografias'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioSocioeconomico',
            fields=[
                ('id_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_escolar_inicial', models.CharField(max_length=100)),
                ('grado_escolar_inicial', models.CharField(max_length=100)),
                ('referencia_ingreso', models.TextField(blank=True, null=True)),
                ('referencia_casa', models.TextField(blank=True, null=True)),
                ('estatus_estudio', models.CharField(max_length=50)),
                ('prioridad_servicio', models.CharField(max_length=50)),
                ('nota_servicio', models.TextField(blank=True, null=True)),
                ('link_documento', models.URLField(blank=True, null=True)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.expediente')),
            ],
            options={
                'db_table': 'estudio_socioeconomico',
            },
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad', models.CharField(max_length=50)),
                ('id_estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudios.estudiosocioeconomico')),
            ],
            options={
                'db_table': 'analisis',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id_familia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido_p', models.CharField(max_length=25)),
                ('apellido_m', models.CharField(max_length=25)),
                ('parentesco', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('actividad_principal', models.CharField(max_length=100)),
                ('area_laboral_escuela', models.CharField(blank=True, max_length=100, null=True)),
                ('salario', models.CharField(blank=True, max_length=100, null=True)),
                ('vive_en_casa', models.BooleanField(default=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('es_tutor_principal', models.BooleanField(default=False)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='beneficiarios.expediente')),
            ],
            options={
                'verbose_name_plural': 'Familiares',
                'db_table': 'familia',
            },
        ),
    ]
