# Generated by Django 6.0.1 on 2026-04-02 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0003_beneficiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio_Socioeconomico',
            fields=[
                ('id_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_escolar_inicial', models.CharField(max_length=25)),
                ('grado_escolar_inicial', models.CharField(max_length=15)),
                ('referencia_ingreso', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_comida_en_casa', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus_estudio', models.CharField(default='En proceso', max_length=50)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='estudios_socioeconomicos', to='beneficiarios.expediente')),
            ],
            options={
                'verbose_name_plural': 'Estudios Socioeconómicos',
                'db_table': 'estudio_socioeconomico',
            },
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico_social', models.TextField()),
                ('sugerencia_apoyo', models.TextField()),
                ('viabilidad', models.CharField(max_length=15)),
                ('fecha_analisis', models.DateField(auto_now_add=True)),
                ('id_estudio', models.OneToOneField(db_column='id_estudio', on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='estudios.estudio_socioeconomico')),
            ],
            options={
                'verbose_name_plural': 'Análisis',
                'db_table': 'analisis',
            },
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id_alimentacion', models.AutoField(primary_key=True, serialize=False)),
                ('frecuencia_carne', models.IntegerField(default=0)),
                ('frecuencia_leche', models.IntegerField(default=0)),
                ('frecuencia_huevo', models.IntegerField(default=0)),
                ('frecuencia_frutas', models.IntegerField(default=0)),
                ('frecuencia_verduras', models.IntegerField(default=0)),
                ('frecuencia_cereales', models.IntegerField(default=0)),
                ('id_estudio', models.OneToOneField(db_column='id_estudio', on_delete=django.db.models.deletion.CASCADE, related_name='alimentacion', to='estudios.estudio_socioeconomico')),
            ],
            options={
                'verbose_name_plural': 'Alimentación',
                'db_table': 'alimentacion',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id_familia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido_p', models.CharField(max_length=25)),
                ('apellido_m', models.CharField(max_length=25)),
                ('parentesco', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('actividad_principal', models.CharField(max_length=100)),
                ('area_laboral_escuela', models.CharField(blank=True, max_length=100, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vive_en_casa', models.BooleanField(default=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('es_tutor_principal', models.BooleanField(default=False)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='beneficiarios.expediente')),
            ],
            options={
                'verbose_name_plural': 'Familiares',
                'db_table': 'familia',
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('alimentacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('luz', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('agua', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('renta', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('educacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('transporte', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('salud', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('id_estudio', models.OneToOneField(db_column='id_estudio', on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='estudios.estudio_socioeconomico')),
            ],
            options={
                'verbose_name_plural': 'Gastos',
                'db_table': 'gastos',
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id_vivienda', models.AutoField(primary_key=True, serialize=False)),
                ('tenencia', models.CharField(max_length=15)),
                ('material_techo', models.CharField(max_length=15)),
                ('material_piso', models.CharField(max_length=15)),
                ('material_muros', models.CharField(max_length=15)),
                ('num_cuartos', models.IntegerField()),
                ('num_dormitorios', models.IntegerField()),
                ('tiene_agua', models.BooleanField(default=False)),
                ('tiene_luz', models.BooleanField(default=False)),
                ('tiene_drenaje', models.BooleanField(default=False)),
                ('tiene_internet', models.BooleanField(default=False)),
                ('id_estudio', models.OneToOneField(db_column='id_estudio', on_delete=django.db.models.deletion.CASCADE, related_name='vivienda', to='estudios.estudio_socioeconomico')),
            ],
            options={
                'verbose_name_plural': 'Viviendas',
                'db_table': 'vivienda',
            },
        ),
    ]
