# Generated by Django 6.0.1 on 2026-04-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='area_laboral_escuela',
        ),
        migrations.AlterField(
            model_name='familia',
            name='apellido_m',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
