# Generated by Django 6.0.1 on 2026-04-07 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios_Vivienda',
            fields=[
                ('id_servicios', models.AutoField(primary_key=True, serialize=False)),
                ('localizacion_bano', models.CharField(max_length=100)),
                ('drenaje', models.BooleanField(default=False)),
                ('tipo_drenaje', models.CharField(blank=True, max_length=100, null=True)),
                ('servicios_basicos', models.CharField(max_length=255)),
                ('aparatos_electronicos', models.TextField(blank=True, null=True)),
                ('aparatos_electrodomesticos', models.TextField(blank=True, null=True)),
                ('id_estudio', models.OneToOneField(db_column='id_estudio', on_delete=django.db.models.deletion.CASCADE, related_name='servicios_vivienda', to='estudios.estudio_socioeconomico')),
            ],
            options={
                'db_table': 'servicios_vivienda',
            },
        ),
        migrations.CreateModel(
            name='Situacion_Familiar',
            fields=[
                ('id_situacion_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('total_personas_casa', models.IntegerField()),
                ('estado_civil_padres', models.CharField(max_length=100)),
                ('hijos_diferente_padre', models.BooleanField(default=False)),
                ('madre_anticonceptivo', models.BooleanField(default=False)),
                ('familiar_enfermo', models.BooleanField(default=False)),
                ('diagnostico', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_cuidados', models.CharField(blank=True, max_length=255, null=True)),
                ('nota_situacion_familiar', models.TextField(blank=True, null=True)),
                ('seguro_medico', models.BooleanField(default=False)),
                ('id_estudio', models.OneToOneField(db_column='id_estudio', on_delete=django.db.models.deletion.CASCADE, related_name='situacion_familiar', to='estudios.estudio_socioeconomico')),
            ],
            options={
                'verbose_name_plural': 'Situaciones Familiares',
                'db_table': 'situacion_familiar',
            },
        ),
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id_sugerencias', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad_servicio_social', models.CharField(max_length=50)),
                ('nota_servicio_social', models.TextField(blank=True, null=True)),
                ('id_estudio', models.OneToOneField(db_column='id_estudio', on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='estudios.estudio_socioeconomico')),
            ],
            options={
                'db_table': 'sugerencias',
            },
        ),
    ]
