# Generated by Django 6.0.1 on 2026-03-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuario',
            new_name='nom_usuario',
        ),
        migrations.AddField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='rol',
            name='permisos',
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, db_table='rol_permiso', related_name='roles', to='cuentas.permiso'),
        ),
    ]
