# Generated by Django 6.0.1 on 2026-03-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('ciclo_escolar', models.CharField(help_text='Ejemplo: 2025-2026', max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Periodos',
                'db_table': 'periodo',
            },
        ),
    ]
