# Generated by Django 6.0.1 on 2026-03-28 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('cp', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_p', models.CharField(max_length=100)),
                ('apellido_m', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=255, null=True)),
                ('nota_situacion_familiar', models.TextField(blank=True, null=True)),
                ('id_direccion', models.ForeignKey(db_column='id_direccion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to='beneficiarios.direccion')),
            ],
            options={
                'verbose_name_plural': 'Expedientes',
                'db_table': 'expediente',
            },
        ),
    ]
