# Generated by Django 6.0.1 on 2026-04-15 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=5)),
                ('colonia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cp', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_p', models.CharField(max_length=15)),
                ('apellido_m', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('genero', models.CharField(max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=30, null=True)),
                ('nota_situacion_familiar', models.TextField(blank=True, null=True)),
                ('id_direccion', models.ForeignKey(db_column='id_direccion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to='beneficiarios.direccion')),
            ],
            options={
                'verbose_name_plural': 'Expedientes',
                'db_table': 'expediente',
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(default='Activo', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='beneficiarios.expediente')),
            ],
            options={
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'beneficiario',
            },
        ),
        migrations.CreateModel(
            name='Fotografias',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('etapa', models.CharField(max_length=50)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='beneficiarios.expediente')),
            ],
            options={
                'db_table': 'fotografias',
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id_postulante', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(default='Pendiente', max_length=50)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='postulantes', to='beneficiarios.expediente')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulantes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Postulantes',
                'db_table': 'postulante',
            },
        ),
        migrations.CreateModel(
            name='Visita_Postulante',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateTimeField()),
                ('estado_visita', models.CharField(default='Programada', max_length=50)),
                ('nota_visita', models.TextField(blank=True, null=True)),
                ('id_postulante', models.ForeignKey(db_column='id_postulante', on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='beneficiarios.postulante')),
            ],
            options={
                'verbose_name_plural': 'Visitas de Postulantes',
                'db_table': 'visita_postulante',
            },
        ),
    ]
