# Generated by Django 6.0.1 on 2026-04-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='apellido_m',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
