# Generated by Django 6.0.1 on 2026-04-01 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='municipio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='apellido_m',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='apellido_p',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='correo',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='genero',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id_postulante', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(default='Pendiente', max_length=50)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='postulantes', to='beneficiarios.expediente')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulantes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Postulantes',
                'db_table': 'postulante',
            },
        ),
        migrations.CreateModel(
            name='Visita_Postulante',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateTimeField()),
                ('estado_visita', models.CharField(default='Programada', max_length=50)),
                ('nota_visita', models.TextField(blank=True, null=True)),
                ('id_postulante', models.ForeignKey(db_column='id_postulante', on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='beneficiarios.postulante')),
            ],
            options={
                'verbose_name_plural': 'Visitas de Postulantes',
                'db_table': 'visita_postulante',
            },
        ),
    ]
