# Generated by Django 6.0.1 on 2026-04-02 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_alter_direccion_calle_alter_direccion_colonia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(default='Activo', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='beneficiarios.expediente')),
            ],
            options={
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'beneficiario',
            },
        ),
    ]
