# Generated by Django 6.0.1 on 2026-04-07 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0003_beneficiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografias',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('etapa', models.CharField(max_length=50)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='beneficiarios.expediente')),
            ],
            options={
                'db_table': 'fotografias',
            },
        ),
    ]
